### PR TITLE
Move FPS counter to right side

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
This completely breaks if the window is resized at all (ie. full-screen).

**Comment by mobilegmYT** [comment]
> This completely breaks if the window is resized at all (ie. full-screen).

That is true, but it's better than the counter blocking the HUD hearts, and afaik there's no way to dynamically move the counter to the right side of the screen.

**Comment by TheBrokenRail** [comment]
> > This completely breaks if the window is resized at all (ie. full-screen).
> 
> That is true, but it's better than the counter blocking the HUD hearts, and afaik there's no way to dynamically move the counter to the right side of the screen.

While the FPS counter *does* cover the hearts, it is translucent and you can still easily tell your health.

**Comment by Alvarito050506** [comment]
Also, you can always use a non-default value, that's why that setting is there after all.

**Pull request closed without merging**
